'use client'

import { useChartStore } from '@/lib/store/chart-store'
import { SIGNS } from '@/lib/calculations/ephemeris'
import { formatDate } from '@/lib/utils'

export function PrintLayout() {
  const { chartData, system } = useChartStore()

  if (!chartData) return null

  return (
    <div className="print:block hidden">
      <div className="max-w-4xl mx-auto p-8 bg-white text-black">
        {/* Header */}
        <div className="text-center mb-8 border-b-2 pb-4">
          <h1 className="text-3xl font-bold text-gray-800">Prerana Astro</h1>
          <h2 className="text-xl text-gray-600 mt-2">
            {system === 'vedic' ? 'Vedic' : system === 'kp' ? 'Krishnamurti Paddhati' : 'Western'} Chart
          </h2>
        </div>

        {/* Chart Wheel Placeholder */}
        <div className="mb-8">
          <h3 className="text-lg font-semibold mb-4">Birth Chart</h3>
          <div className="h-80 border-2 border-gray-300 rounded-lg flex items-center justify-center bg-gray-50">
            <p className="text-gray-500">Chart visualization would appear here</p>
          </div>
        </div>

        {/* Planetary Positions Table */}
        <div className="mb-8">
          <h3 className="text-lg font-semibold mb-4">Planetary Positions</h3>
          <table className="w-full border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-4 py-2 text-left">Planet</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Sign</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Degree</th>
                <th className="border border-gray-300 px-4 py-2 text-left">House</th>
                <th className="border border-gray-300 px-4 py-2 text-left">Nakshatra</th>
              </tr>
            </thead>
            <tbody>
              {chartData.planets.map((planet) => (
                <tr key={planet.name}>
                  <td className="border border-gray-300 px-4 py-2 font-medium">{planet.name}</td>
                  <td className="border border-gray-300 px-4 py-2">{SIGNS[planet.sign!]}</td>
                  <td className="border border-gray-300 px-4 py-2">{planet.degree}°{planet.minute}'</td>
                  <td className="border border-gray-300 px-4 py-2">{planet.house}</td>
                  <td className="border border-gray-300 px-4 py-2">
                    {Math.floor((planet.longitude % 360) / (360 / 27)) + 1}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* House Cusps */}
        <div className="mb-8">
          <h3 className="text-lg font-semibold mb-4">House Cusps</h3>
          <div className="grid grid-cols-4 gap-4">
            {chartData.houses.map((house) => (
              <div key={house.house} className="border border-gray-300 p-3 text-center">
                <div className="font-semibold">House {house.house}</div>
                <div className="text-sm text-gray-600">
                  {SIGNS[house.sign]} {house.degree}°{house.minute}'
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-sm text-gray-500 mt-8 pt-4 border-t">
          <p>Generated by Prerana Astro • {new Date().toLocaleDateString()}</p>
          <p>For educational and entertainment purposes only</p>
        </div>
      </div>
    </div>
  )
}

export function printChart() {
  window.print()
}